package org.example.java_final_project.Server.DAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ConnectDB {
    protected Connection conn ;
    protected Statement statement ;
    public Connection OpenConnection() {
        final String DATABASE_NAME = "jdbc:mysql://localhost:3306/dangnhap";
        final String USER = "root" ;
        final String password = "";
        try{
            Class.forName("com.mysql.jdbc.Driver") ;
            conn = DriverManager.getConnection(DATABASE_NAME,USER,password) ;
        }catch (Exception e){
            e.printStackTrace();
        }
        return conn ;
    }
    public void CloseConnection() {
        try{
            if(conn != null && !conn.isClosed()){
                conn.close();
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    public int executeQuery(String sql) {
        // returns the ResultSet object generated by the query.
        int n = 0 ;
        try {
            statement = conn.createStatement();
            n  = statement.executeUpdate(sql) ;
        }catch (Exception e){
            e.printStackTrace();
        }
        return n  ;
    }
}
